# Generated by Django 6.0.4 on 2026-04-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('empleado', 'Empleado'), ('visitante', 'Visitante'), ('administrador', 'Administrador'), ('contratista', 'Contratista')], default='empleado', max_length=20)),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_acceso', models.IntegerField(choices=[(1, 'Nivel 1 - Público'), (2, 'Nivel 2 - Empleados'), (3, 'Nivel 3 - Restringido'), (4, 'Nivel 4 - Alta Seguridad')], default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nivel_acceso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('resultado', models.CharField(choices=[('permitido', 'Acceso Permitido'), ('denegado', 'Acceso Denegado'), ('sin_permiso', 'Sin Permiso'), ('caducado', 'Permiso Caducado')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='control_accesos.usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='control_accesos.zona')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('caducado', 'Caducado'), ('revocado', 'Revocado'), ('pendiente', 'Pendiente')], default='activo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='control_accesos.usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='control_accesos.zona')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
