# Generated by Django 6.0.1 on 2026-05-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_accesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={},
        ),
        migrations.AlterField(
            model_name='permiso',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('caducado', 'Caducado'), ('revocado', 'Revocado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='resultado',
            field=models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('visitante', 'Visitante'), ('contratista', 'Contratista'), ('admin', 'Administrador')], default='empleado', max_length=20),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nivel_acceso',
            field=models.IntegerField(choices=[(1, 'Nivel 1 – Público'), (2, 'Nivel 2 – Restringido'), (3, 'Nivel 3 – Confidencial'), (4, 'Nivel 4 – Alta seguridad')], default=1),
        ),
    ]
